### ISSUE TITLE
Calculations with CAR do not work with example data

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#191]
@christophfink : Following the examples and using our sample data does not seem to work when using `CAR` as the travel mode (I assume this should work?):

```python
import geopandas 
import datetime
from r5py import TravelTimeMatrixComputer, TransitMode, LegMode, TransportNetwork

points_url = "https://github.com/r5py/r5py/raw/main/docs/data/Helsinki/population_points_2020.gpkg"
points = geopandas.read_file(points_url)
origin = points.loc[points["id"] == 54].copy()

transport_network = TransportNetwork(
    "../data/Helsinki/kantakaupunki.osm.pbf",
    [
        "../data/Helsinki/GTFS.zip"
    ]
)

travel_time_matrix_computer = TravelTimeMatrixComputer(
    transport_network,
    origins=origin,
    destinations=points,
    departure=datetime.datetime(2022,2,22,8,30),
    transport_modes=[LegMode.CAR]
)
travel_time_matrix = travel_time_matrix_computer.compute_travel_times()
travel_time_matrix.head()
```

This produces following error (partially truncated):
![image](https://user-images.githubusercontent.com/6659534/190236032-7f6ecd21-e1f1-464b-be52-c59790b4fc32.png)

![image](https://user-images.githubusercontent.com/6659534/190236242-a77ac674-a009-4432-9bae-75b49db8a350.png)

**Comment by christophfink** [comment]
The Java stacktrace:

```
/ by zero java.lang.ArithmeticException: / by zero
	at com.conveyal.r5.streets.LinkedPointSet.timeToPoint(LinkedPointSet.java:617)
	at com.conveyal.r5.streets.LinkedPointSet.eval(LinkedPointSet.java:456)
	at com.conveyal.r5.analyst.TravelTimeComputer.computeTravelTimes(TravelTimeComputer.java:217)
```

**Comment by christophfink** [comment]
`com.conveyal.r5.streets.LinkedPointSet.timeToPoint(LinkedPointSet.java:617` is the following:

```
time0 += distances0_mm[pointIndex] / onStreetSpeed + offStreetTime;
```

so there seem to be some street segments for which we don’t have an `onStreetSpeed` (not sure what that exactly means, but it’s a clue)

**Comment by christophfink** [comment]
[car-error.py.txt](https://github.com/r5py/r5py/files/9575426/car-error.py.txt)
 
(this reproduces the error and creates a stacktrace)

**Comment by christophfink** [comment]
```
[Thread-2] WARN  c.c.r.s.StreetRouter - A state's time is being incremented by a negative amount while traversing edge
```

**Comment by christophfink** [comment]
[car.log](https://github.com/r5py/r5py/files/9663458/car.log)

**Comment by christophfink** [comment]
```
Warning: SIGILL handler modified!
Signal Handlers:
   SIGSEGV: 0x00007fac8bfb0500 in libjvm.so+14353664, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO
    SIGBUS: 0x00007fac8bfb0500 in libjvm.so+14353664, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO
    SIGFPE: 0x00007fac8bfb0500 in libjvm.so+14353664, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO
   SIGPIPE: 0x00007fac8bfb0500 in libjvm.so+14353664, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO
   SIGXFSZ: 0x00007fac8bfb0500 in libjvm.so+14353664, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO
    SIGILL: 0x00007fac8bfb0500 in libjvm.so+14353664, mask=00010000000000000000000000000000, flags=SA_RESTART
  *** Handler was modified!
  *** Expected: 0x00007fac8bfb0500 in libjvm.so+14353664, mask=11100100110111111111111111111110, flags=SA_RESTART|SA_SIGINFO
   SIGUSR2: 0x00007fac8bfafc00 in libjvm.so+14351360, mask=00000000000000000000000000000000, flags=SA_RESTART|SA_SIGINFO
    SIGHUP: 0x00007fac8bfafb10 in libjvm.so+14351120, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO
    SIGINT: 0x00007fac8bfafb10 in libjvm.so+14351120, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO
   SIGTERM: 0x00007fac8bfafb10 in libjvm.so+14351120, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO
   SIGQUIT: 0x00007fac8bfafb10 in libjvm.so+14351120, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO
   SIGTRAP: SIG_DFL, mask=00000000000000000000000000000000, flags=none
Consider using jsig library.
2022-09-28 12:06:26,046 [main] INFO  c.c.o.OSM - OSM will be stored in file /home/christoph/.cache/r5py/TransportNetwork_7fa2effbde4/paakaupunkiseutu_unfiltered.pbf.mapdb.
2022-09-28 12:06:26,354 [main] INFO  c.c.o.OSM - No OSM tables exist yet, they will be created.
2022-09-28 12:06:26,358 [main] INFO  c.c.o.OSM - Reading OSM from file '/home/christoph/.cache/r5py/TransportNetwork_7fa2effbde4/paakaupunkiseutu_unfiltered.pbf'.
2022-09-28 12:06:26,372 [main] INFO  c.c.o.PBFInput - PBF file has no replication timestamp.
2022-09-28 12:06:26,384 [main] INFO  c.c.o.PBFInput - node 1
2022-09-28 12:06:28,681 [main] INFO  c.c.o.PBFInput - way 1
2022-09-28 12:06:29,987 [main] INFO  c.c.o.PBFInput - relation 1
2022-09-28 12:06:30,447 [main] INFO  c.c.o.PBFInput - Done parsing PBF.
2022-09-28 12:06:30,447 [main] INFO  c.c.o.PBFInput - Read 3499818 nodes, 537536 ways, 7112 relations.
Summarizing builder config: build-config.json
{
  "htmlAnnotations" : false,
  "maxHtmlAnnotationsPerFile" : 1000,
  "transit" : true,
  "useTransfersTxt" : false,
  "parentStopLinking" : false,
  "stationTransfers" : false,
  "subwayAccessTime" : 2.0,
  "streets" : true,
  "embedRouterConfig" : true,
  "areaVisibility" : false,
  "matchBusRoutesToStreets" : false,
  "fetchElevationUS" : false,
  "speeds" : {
    "units" : "mph",
    "values" : {
      "motorway" : 65,
      "motorway_link" : 35,
      "trunk" : 55,
      "trunk_link" : 35,
      "primary" : 45,
      "primary_link" : 25,
      "secondary" : 35,
      "secondary_link" : 25,
      "tertiary" : 25,
      "tertiary_link" : 25,
      "living_street" : 5
    },
    "defaultSpeed" : 0
  },
  "staticBikeRental" : false,
  "staticParkAndRide" : true,
  "staticBikeParkAndRide" : false,
  "bikeRentalFile" : null,
  "analysisFareCalculator" : null
}
2022-09-28 12:06:30,524 [main] INFO  c.c.r.s.StreetLayer - Making street edges from OSM ways...
2022-09-28 12:06:30,536 [main] ERROR c.c.r.s.StreetLayer - Continuing to load but ignoring generalized costs due to exception: java.lang.RuntimeException: All ways are expected to have generalized cost tags. Missing: slope_1:forward
2022-09-28 12:06:34,581 [main] ERROR c.c.r.l.TraversalPermissionLabeler - Way has tags bicycle:forward=use_sidepath and bicycle:backward=use_sidepath please use bicycle=use_sidepath
2022-09-28 12:06:34,581 [main] ERROR c.c.r.l.TraversalPermissionLabeler - Way has tags bicycle:forward=use_sidepath and bicycle:backward=use_sidepath please use bicycle=use_sidepath
2022-09-28 12:06:34,750 [main] WARN  c.c.r.l.LevelOfTrafficStressLabeler - Unrecognized values for lane tag: [1.5, 1.8]
2022-09-28 12:06:34,750 [main] INFO  c.c.r.s.StreetLayer - This street layer does not contain per-edge traversal and turn times.
2022-09-28 12:06:34,760 [main] INFO  c.c.r.s.StreetLayer - Surrogate LTS:
  1: 790126 edges
  2: 40390 edges
  3: 12258 edges
  4: 61112 edges
  Unknown: 195280 edges
2022-09-28 12:06:35,032 [main] INFO  c.c.r.s.StreetLayer - Done making street edges.
2022-09-28 12:06:35,032 [main] INFO  c.c.r.s.StreetLayer - Made 417223 vertices and 1099166 edges.
2022-09-28 12:06:35,033 [main] INFO  c.c.r.s.StreetLayer - Found 4 P+R node candidates
2022-09-28 12:06:35,033 [main] INFO  c.c.r.s.StreetLayer - Building edge lists from edges...
2022-09-28 12:06:35,180 [main] INFO  c.c.r.s.StreetLayer - Done building edge lists.
2022-09-28 12:06:35,323 [main] INFO  c.c.r.s.TarjanIslandPruner - Removing islands for mode CAR
2022-09-28 12:06:35,678 [main] INFO  c.c.r.s.TarjanIslandPruner - Found 218428 strong components for mode CAR using Tarjan's algorithm in 0.355sec
2022-09-28 12:06:35,733 [main] INFO  c.c.r.s.TarjanIslandPruner - Removed 218413 strong component (islands) with fewer than 40 vertices for mode CAR in 0.054sec. 224606 vertices removed.
2022-09-28 12:06:35,734 [main] INFO  c.c.r.s.TarjanIslandPruner - Removing islands for mode WALK
2022-09-28 12:06:36,012 [main] INFO  c.c.r.s.TarjanIslandPruner - Found 16657 strong components for mode WALK using Tarjan's algorithm in 0.278sec
2022-09-28 12:06:36,026 [main] INFO  c.c.r.s.TarjanIslandPruner - Removed 16653 strong component (islands) with fewer than 40 vertices for mode WALK in 0.013sec. 21661 vertices removed.
2022-09-28 12:06:36,027 [main] INFO  c.c.r.s.TarjanIslandPruner - Removing islands for mode BICYCLE
2022-09-28 12:06:36,311 [main] INFO  c.c.r.s.TarjanIslandPruner - Found 19239 strong components for mode BICYCLE using Tarjan's algorithm in 0.284sec
2022-09-28 12:06:36,315 [main] INFO  c.c.r.s.TarjanIslandPruner - Removed 19235 strong component (islands) with fewer than 40 vertices for mode BICYCLE in 0.004sec. 21146 vertices removed.
2022-09-28 12:06:36,315 [main] INFO  c.c.r.s.StreetLayer - Indexing streets...
2022-09-28 12:06:36,547 [main] INFO  c.c.r.s.StreetLayer - Done indexing streets.
2022-09-28 12:06:37,253 [main] INFO  c.c.r.s.StreetLayer - Made 119 P+R vertices
2022-09-28 12:06:37,474 [main] ERROR c.c.r.s.StreetLayer - Invalid turn restriction 14004, does not have from, to and via, skipping
2022-09-28 12:06:37,475 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 14152, skipping
2022-09-28 12:06:37,481 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 57333, skipping
2022-09-28 12:06:37,483 [main] ERROR c.c.r.s.StreetLayer - Invalid turn restriction 58947, does not have from, to and via, skipping
2022-09-28 12:06:37,483 [main] WARN  c.c.r.s.StreetLayer - Vertex 317705822 not found to use as via node for restriction 58949, skipping this restriction
2022-09-28 12:06:37,485 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 59265, skipping
2022-09-28 12:06:37,486 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 59266, skipping
2022-09-28 12:06:37,486 [main] ERROR c.c.r.s.StreetLayer - Invalid turn restriction 59277, does not have from, to and via, skipping
2022-09-28 12:06:37,487 [main] ERROR c.c.r.s.StreetLayer - Invalid turn restriction 61323, does not have from, to and via, skipping
2022-09-28 12:06:37,488 [main] WARN  c.c.r.s.StreetLayer - Vertex 1533407983 not found to use as via node for restriction 68464, skipping this restriction
2022-09-28 12:06:37,488 [main] ERROR c.c.r.s.StreetLayer - Invalid turn restriction 68469, does not have from, to and via, skipping
2022-09-28 12:06:37,488 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 68486, skipping
2022-09-28 12:06:37,489 [main] ERROR c.c.r.s.StreetLayer - Invalid turn restriction 68497, does not have from, to and via, skipping
2022-09-28 12:06:37,489 [main] ERROR c.c.r.s.StreetLayer - Invalid turn restriction 68499, does not have from, to and via, skipping
2022-09-28 12:06:37,489 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 68512, skipping
2022-09-28 12:06:37,490 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 68514, skipping
2022-09-28 12:06:37,491 [main] ERROR c.c.r.s.StreetLayer - Invalid turn restriction 68893, does not have from, to and via, skipping
2022-09-28 12:06:37,491 [main] ERROR c.c.r.s.StreetLayer - Invalid turn restriction 68894, does not have from, to and via, skipping
2022-09-28 12:06:37,491 [main] ERROR c.c.r.s.StreetLayer - Invalid turn restriction 68895, does not have from, to and via, skipping
2022-09-28 12:06:37,492 [main] ERROR c.c.r.s.StreetLayer - Invalid turn restriction 68897, does not have from, to and via, skipping
2022-09-28 12:06:37,494 [main] ERROR c.c.r.s.StreetLayer - Restriction 68978 has no restriction tag, skipping
2022-09-28 12:06:37,495 [main] ERROR c.c.r.s.StreetLayer - Invalid turn restriction 68991, does not have from, to and via, skipping
2022-09-28 12:06:37,495 [main] ERROR c.c.r.s.StreetLayer - Invalid turn restriction 69215, does not have from, to and via, skipping
2022-09-28 12:06:37,498 [main] ERROR c.c.r.s.StreetLayer - Turn restriction 84325 has multiple 'to' members, skipping.
2022-09-28 12:06:37,498 [main] ERROR c.c.r.s.StreetLayer - Turn restriction 84326 has multiple 'from' members, skipping.
2022-09-28 12:06:37,501 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 299100, skipping
2022-09-28 12:06:37,501 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 423033, skipping
2022-09-28 12:06:37,501 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 423034, skipping
2022-09-28 12:06:37,502 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 949202, skipping
2022-09-28 12:06:37,503 [main] WARN  c.c.r.s.StreetLayer - Did not find via way 65067021 for restriction 1019845, skipping
2022-09-28 12:06:37,503 [main] WARN  c.c.r.s.StreetLayer - Did not find via way 65067021 for restriction 1019846, skipping
2022-09-28 12:06:37,505 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 1773114, skipping
2022-09-28 12:06:37,509 [main] ERROR c.c.r.s.StreetLayer - Invalid turn restriction 2715559, does not have from, to and via, skipping
2022-09-28 12:06:37,509 [main] ERROR c.c.r.s.StreetLayer - Restriction 2818346 has no restriction tag, skipping
2022-09-28 12:06:37,509 [main] ERROR c.c.r.s.StreetLayer - Restriction 2818347 has no restriction tag, skipping
2022-09-28 12:06:37,509 [main] ERROR c.c.r.s.StreetLayer - Invalid turn restriction 2844181, does not have from, to and via, skipping
2022-09-28 12:06:37,509 [main] ERROR c.c.r.s.StreetLayer - Restriction 2886802 has no restriction tag, skipping
2022-09-28 12:06:37,509 [main] ERROR c.c.r.s.StreetLayer - Restriction 2886803 has no restriction tag, skipping
2022-09-28 12:06:37,509 [main] ERROR c.c.r.s.StreetLayer - Restriction 2886879 has no restriction tag, skipping
2022-09-28 12:06:37,509 [main] ERROR c.c.r.s.StreetLayer - Restriction 2886880 has no restriction tag, skipping
2022-09-28 12:06:37,510 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 2891693, skipping
2022-09-28 12:06:37,510 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 2963509, skipping
2022-09-28 12:06:37,510 [main] ERROR c.c.r.s.StreetLayer - Restriction 3081329 has no restriction tag, skipping
2022-09-28 12:06:37,510 [main] ERROR c.c.r.s.StreetLayer - Restriction 3081330 has no restriction tag, skipping
2022-09-28 12:06:37,510 [main] ERROR c.c.r.s.StreetLayer - Restriction 3297476 has no restriction tag, skipping
2022-09-28 12:06:37,510 [main] ERROR c.c.r.s.StreetLayer - Restriction 3297477 has no restriction tag, skipping
2022-09-28 12:06:37,510 [main] ERROR c.c.r.s.StreetLayer - Restriction 3297478 has no restriction tag, skipping
2022-09-28 12:06:37,511 [main] ERROR c.c.r.s.StreetLayer - Invalid turn restriction 3784122, no way from from to to via via, skipping
2022-09-28 12:06:37,511 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 3860298, skipping
2022-09-28 12:06:37,511 [main] ERROR c.c.r.s.StreetLayer - Invalid turn restriction 3878444, does not have from, to and via, skipping
2022-09-28 12:06:37,512 [main] ERROR c.c.r.s.StreetLayer - Restriction 4072773 has no restriction tag, skipping
2022-09-28 12:06:37,512 [main] ERROR c.c.r.s.StreetLayer - Restriction 4072774 has no restriction tag, skipping
2022-09-28 12:06:37,512 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 4226282, skipping
2022-09-28 12:06:37,512 [main] WARN  c.c.r.s.StreetLayer - Vertex 248791566 not found to use as via node for restriction 4453377, skipping this restriction
2022-09-28 12:06:37,513 [main] ERROR c.c.r.s.StreetLayer - Restriction 5463268 has no restriction tag, skipping
2022-09-28 12:06:37,513 [main] ERROR c.c.r.s.StreetLayer - Restriction 5470217 has no restriction tag, skipping
2022-09-28 12:06:37,513 [main] ERROR c.c.r.s.StreetLayer - Restriction 5470218 has no restriction tag, skipping
2022-09-28 12:06:37,513 [main] ERROR c.c.r.s.StreetLayer - Restriction 5470219 has no restriction tag, skipping
2022-09-28 12:06:37,515 [main] ERROR c.c.r.s.StreetLayer - Restriction 7535881 has no restriction tag, skipping
2022-09-28 12:06:37,515 [main] ERROR c.c.r.s.StreetLayer - Restriction 7535882 has no restriction tag, skipping
2022-09-28 12:06:37,515 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 7681394, skipping
2022-09-28 12:06:37,515 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 7725015, skipping
2022-09-28 12:06:37,515 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 8177250, skipping
2022-09-28 12:06:37,516 [main] ERROR c.c.r.s.StreetLayer - Invalid turn restriction 9388736, does not have from, to and via, skipping
2022-09-28 12:06:37,519 [main] ERROR c.c.r.s.StreetLayer - Restriction 13479835 has no restriction tag, skipping
2022-09-28 12:06:37,519 [main] WARN  c.c.r.s.StreetLayer - Did not find from/to edges for restriction 13480171, skipping
2022-09-28 12:06:37,520 [main] INFO  c.c.r.s.StreetLayer - Created 1246 turn restrictions
2022-09-28 12:06:38,839 [main] INFO  c.c.r.s.StreetLayer - Indexing streets...
2022-09-28 12:06:39,070 [main] INFO  c.c.r.s.StreetLayer - Done indexing streets.
2022-09-28 12:06:39,301 [main] INFO  c.c.g.m.Entity$Loader - Loading GTFS table feed_info from feed_info.txt
2022-09-28 12:06:39,305 [main] INFO  c.c.g.GTFSFeed - No feedId supplied and feed does not declare one. Using file name GTFS.
2022-09-28 12:06:39,305 [main] INFO  c.c.g.m.Entity$Loader - Loading GTFS table agency from agency.txt
2022-09-28 12:06:39,306 [main] INFO  c.c.g.m.Entity$Loader - Loading GTFS table calendar from calendar.txt
2022-09-28 12:06:39,307 [main] INFO  c.c.g.m.Entity$Loader - Table calendar_dates was missing but it is not required.
2022-09-28 12:06:39,307 [main] INFO  c.c.g.m.Entity$Loader - Loading GTFS table fare_attributes from fare_attributes.txt
2022-09-28 12:06:39,308 [main] INFO  c.c.g.m.Entity$Loader - Loading GTFS table fare_rules from fare_rules.txt
2022-09-28 12:06:39,309 [main] INFO  c.c.g.m.Entity$Loader - Loading GTFS table routes from routes.txt
2022-09-28 12:06:39,317 [main] INFO  c.c.g.m.Entity$Loader - Loading GTFS table shapes from shapes.txt
2022-09-28 12:06:39,565 [main] INFO  c.c.g.m.Entity$Loader - Loading GTFS table stops from stops.txt
2022-09-28 12:06:39,591 [main] INFO  c.c.g.m.Entity$Loader - Loading GTFS table transfers from transfers.txt
2022-09-28 12:06:39,592 [main] INFO  c.c.g.m.Entity$Loader - Loading GTFS table trips from trips.txt
2022-09-28 12:06:39,610 [main] INFO  c.c.g.m.Entity$Loader - Loading GTFS table frequencies from frequencies.txt
2022-09-28 12:06:39,626 [main] INFO  c.c.g.m.Entity$Loader - Loading GTFS table stop_times from stop_times.txt
2022-09-28 12:06:39,930 [main] INFO  c.c.g.GTFSFeed - Generating unique names for patterns
2022-09-28 12:06:39,946 [main] INFO  c.c.g.GTFSFeed - Total patterns: 412
2022-09-28 12:06:39,946 [main] INFO  c.c.g.GTFSFeed - Detected 0 errors in feed.
2022-09-28 12:06:40,254 [main] INFO  c.c.r.t.TransitLayer - Creating trip patterns and schedules.
2022-09-28 12:06:40,259 [main] WARN  c.c.r.t.TripSchedule - GTFS frequency entries with exact_times are not supported, treating as inexact!
2022-09-28 12:06:40,260 [main] WARN  c.c.r.t.TripSchedule - GTFS frequency entries with exact_times are not supported, treating as inexact!
    ... REPEATED 3223 TIMES ...
2022-09-28 12:06:40,583 [main] INFO  c.c.r.t.TransitLayer - Done creating 3195 trips on 412 patterns.
2022-09-28 12:06:40,583 [main] INFO  c.c.r.t.TransitLayer - 4315 zero-duration hops found.
2022-09-28 12:06:40,583 [main] INFO  c.c.r.t.TransitLayer - Chaining trips together according to blocks to model interlining...
2022-09-28 12:06:40,584 [main] INFO  c.c.r.t.TransitLayer - Done chaining trips together according to blocks.
2022-09-28 12:06:40,584 [main] INFO  c.c.r.t.TransitLayer - Sorting trips on each pattern
2022-09-28 12:06:40,585 [main] INFO  c.c.r.t.TransitLayer - done sorting
2022-09-28 12:06:40,586 [main] INFO  c.c.r.t.TransitLayer - Finding the approximate center of the transport network...
2022-09-28 12:06:40,586 [main] INFO  c.c.r.t.TransitLayer - TransportNetwork time zone set to Europe/Helsinki from agency 'Helsingin seudun liikenne' and agency_timezone:Europe/Helsinki
2022-09-28 12:06:40,586 [main] INFO  c.c.r.s.StreetLayer - Indexing streets...
2022-09-28 12:06:40,735 [main] INFO  c.c.r.s.StreetLayer - Done indexing streets.
2022-09-28 12:06:40,972 [main] INFO  c.c.r.s.StreetLayer - Building edge lists from edges...
2022-09-28 12:06:41,027 [main] INFO  c.c.r.s.StreetLayer - Done building edge lists.
2022-09-28 12:06:41,027 [main] INFO  c.c.r.t.TransitLayer - Rebuilding transient indices.
2022-09-28 12:06:41,030 [main] INFO  c.c.r.t.TransitLayer - Done rebuilding transient indices.
2022-09-28 12:06:41,030 [main] INFO  c.c.r.t.TransferFinder - Finding transfers through the street network from 1388 stops...
2022-09-28 12:06:42,533 [main] INFO  c.c.r.t.TransferFinder - Done finding transfers. 0 stops were not linked to the street network.
2022-09-28 12:06:42,533 [main] INFO  c.c.r.t.TransferFinder - Finding closest stops to P+R for 119 P+Rs
2022-09-28 12:06:42,623 [main] INFO  c.c.r.t.TransferFinder - Found 0 unconnected P+Rs and 97 P+Rs without closest stop in 500 m
2022-09-28 12:06:42,625 [main] INFO  c.c.r.t.TransitLayer - Finding distances from transit stops to street vertices.
2022-09-28 12:06:46,656 [ForkJoinPool.commonPool-worker-13] INFO  c.c.r.t.TransitLayer - Computed distances to street vertices from 1000 of 1388 transit stops.
2022-09-28 12:06:49,504 [main] INFO  c.c.r.t.TransitLayer - Done. Computed distances to street vertices from 1388 of 1388 transit stops.
2022-09-28 12:06:49,533 [main] INFO  c.c.r.a.LinkageCache - Seeking linkage for (com.conveyal.r5.analyst.FreeFormPointSet@2b0e9f30, StreetLayer(base), CAR) in cache...
2022-09-28 12:06:49,538 [main] INFO  c.c.r.a.LinkageCache - Building Linkage for (com.conveyal.r5.analyst.FreeFormPointSet@2b0e9f30, StreetLayer(base), CAR) because it was not found in cache.
2022-09-28 12:06:49,538 [main] INFO  c.c.r.s.LinkedPointSet - Linking pointset to street network...
2022-09-28 12:06:49,543 [main] INFO  c.c.r.s.LinkedPointSet - Done. Linked 91 of 91 PointSet points to streets.
2022-09-28 12:06:49,543 [main] INFO  c.c.r.s.LinkedPointSet -       0 of 91 point linkages were copied directly from a source linkage;
2022-09-28 12:06:49,543 [main] INFO  c.c.r.s.LinkedPointSet -       the remaining 91 linkages were refreshed, of which 0 changed;
2022-09-28 12:06:49,543 [main] INFO  c.c.r.s.LinkedPointSet -       of which 0 changed to added edges, 0 to baseline edges, and 0 became unlinked.
2022-09-28 12:06:49,556 [Thread-2] INFO  c.c.r.a.TravelTimeComputer - Performing street search for mode: CAR
2022-09-28 12:06:49,557 [Thread-2] WARN  c.c.r.s.StreetRouter - A state's time is being incremented by a negative amount while traversing edge 
    ... REPEATED 86036922 TIMES ...
2022-09-28 12:11:02,394 [Thread-2] INFO  c.c.r.a.LinkageCache - Seeking linkage for (com.conveyal.r5.analyst.FreeFormPointSet@2b0e9f30, StreetLayer(base), CAR) in cache...
/ by zero java.lang.ArithmeticException: / by zero
	at com.conveyal.r5.streets.LinkedPointSet.timeToPoint(LinkedPointSet.java:617)
	at com.conveyal.r5.streets.LinkedPointSet.eval(LinkedPointSet.java:456)
	at com.conveyal.r5.analyst.TravelTimeComputer.computeTravelTimes(TravelTimeComputer.java:217)
```
