### ISSUE TITLE
Getting `FileNotFoundError` messages on temp file cleanups

### ISSUE THREAD

**Issue by wklumpen** [r5py/r5py#279]
After a run of the latest version of R5py (installed from the head) I receive the following error message after running a travel time computation:

```
Exception ignored in: <function TransportNetwork.__del__ at 0x7fc3d049b700>
Traceback (most recent call last):
  File "/home/willem/mambaforge/envs/ttc-wifi-39/lib/python3.9/site-packages/r5py/r5/transport_network.py", line 125, in __del__
  File "/home/willem/mambaforge/envs/ttc-wifi-39/lib/python3.9/shutil.py", line 724, in rmtree
  File "/home/willem/mambaforge/envs/ttc-wifi-39/lib/python3.9/shutil.py", line 722, in rmtree
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/r5py4v6f2mof/TransportNetwork_7fc46e7c7f1'
```

Running on Ubuntu 22.04-2 LTS, Python 3.9 in a conda environment.

**Comment by christophfink** [comment]
Does this happen after an exception, or also on successful runs?

**Comment by christophfink** [comment]
With #275 `TransportNetwork` handling its own temp files has become redundant, and we can, in fact, remove these `__del__` routines altogether, as we have one big clean-up operation after the JVM stops

**Comment by wklumpen** [comment]
Happened on successful run - I see you've found the issue.
