### ISSUE TITLE
java.lang.RuntimeException after completing the travel time calculation 

### ISSUE THREAD

**Issue by shiqin-liu** [r5py/r5py#366]
**Describe the bug**
I imported R5py as a Python module in a script to run the travel time calculation. I get this Java error at the end every time I complete the calculation. Look like Java stops running when R5py attempts to delete some files. It does not seem to affect the overall calculation process and the result outputs though.

```
Exception in thread "MapDB shutdown hook" java.lang.RuntimeException: java.lang.InterruptedException
	at org.mapdb.AsyncWriteEngine.close(AsyncWriteEngine.java:443)
	at org.mapdb.EngineWrapper.close(EngineWrapper.java:81)
	at org.mapdb.Caches$HashTable.close(Caches.java:328)
	at org.mapdb.EngineWrapper.close(EngineWrapper.java:81)
	at org.mapdb.EngineWrapper$CloseOnJVMShutdown.close(EngineWrapper.java:586)
	at org.mapdb.EngineWrapper$CloseOnJVMShutdown$1.run(EngineWrapper.java:571)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1081)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369)
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
	at org.mapdb.AsyncWriteEngine.close(AsyncWriteEngine.java:435)
	... 6 more
Exception ignored in: <function TransportNetwork.__del__ at 0x14b3dbd90>
Traceback (most recent call last):
  File "/Users/ssliu/.pyenv/versions/nae/lib/python3.10/site-packages/r5py/r5/transport_network.py", line 98, in __del__
jpype._core.JVMNotRunning: Java Virtual Machine is not running
```

**Environment:**
 - MacOS
 - Python package source (PyPi)
 - Python 3.10, Java Development Kit 11

Any insight on this would be appreciated!

**Comment by christophfink** [comment]
Thanks for reporting this. I think it’s more the order in which items are destroyed, i.e., it seems the JVM has already been stopped when the `TransportNetwork`’s destructor is called. Getting rid of this exception should be rather easy, and since it’s in the destructor, there’s not much havoc it can cause. I’ll try something :)
