### ISSUE TITLE
DetailedItineraries StreetPath downstream error: `java.util.NoSuchElementException`

### ISSUE THREAD

**Issue by wklumpen** [r5py/r5py#381]
I'm able to run a smaller batch of itineraries on the same data just fine, but when I tried to run a full matrix I got the following:

```
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "StreetPath.java", line 53, in com.conveyal.r5.profile.StreetPath.<init>
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/envs/ted-dev/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 273, in _wrap_func_call
    return func()
  File "/home/ubuntu/miniforge3/envs/ted-dev/lib/python3.10/site-packages/joblib/parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
  File "/home/ubuntu/miniforge3/envs/ted-dev/lib/python3.10/site-packages/joblib/parallel.py", line 589, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/ubuntu/r5py/src/r5py/r5/detailed_itineraries_computer.py", line 200, in _travel_details_per_od_pair
    trips = trip_planner.trips
  File "/home/ubuntu/r5py/src/r5py/r5/trip_planner.py", line 82, in trips
    trips = self.direct_paths + self.transit_paths
  File "/home/ubuntu/r5py/src/r5py/r5/trip_planner.py", line 135, in direct_paths
    street_segment = self._street_segment_from_router_state(
  File "/home/ubuntu/r5py/src/r5py/r5/trip_planner.py", line 157, in _street_segment_from_router_state
    street_path = com.conveyal.r5.profile.StreetPath(
java.util.java.util.NoSuchElementException: java.util.NoSuchElementException
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/ted-data/scratch.py", line 59, in <module>
    ig.generate_itineraries()
  File "/home/ubuntu/ted-data/ted/fare.py", line 74, in generate_itineraries
    travel_details = computer.compute_travel_details()
  File "/home/ubuntu/r5py/src/r5py/r5/detailed_itineraries_computer.py", line 154, in compute_travel_details
    parallel(
  File "/home/ubuntu/miniforge3/envs/ted-dev/lib/python3.10/site-packages/joblib/parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
  File "/home/ubuntu/miniforge3/envs/ted-dev/lib/python3.10/site-packages/joblib/parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "/home/ubuntu/miniforge3/envs/ted-dev/lib/python3.10/site-packages/joblib/parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "/home/ubuntu/miniforge3/envs/ted-dev/lib/python3.10/site-packages/joblib/parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/ubuntu/miniforge3/envs/ted-dev/lib/python3.10/site-packages/joblib/parallel.py", line 736, in get_result
    return self._return_or_raise()
  File "/home/ubuntu/miniforge3/envs/ted-dev/lib/python3.10/site-packages/joblib/parallel.py", line 754, in _return_or_raise
    raise self._result
java.util.java.util.NoSuchElementException: java.util.NoSuchElementException
```

It seems like there are instances where a StreetPath can't initialize? For reference, I believe it's referring to [this line in R5's `StreetPath.java`](https://github.com/conveyal/r5/blob/e857fcd8be5e6a16166c10e060809c9fe0a3dca0/src/main/java/com/conveyal/r5/profile/StreetPath.java#L53).

Bit of a stretch to diagnose but I thought I'd throw it out there just in case @christophfink recognized it from some earlier development.

**Comment by christophfink** [comment]
@wklumpen has this occurred since? I’m trying to clean up our open issues and this would be a candidate for the archive
